namePrefix: kustomize-

resources:
- test-app-deployment.yaml
- test-app-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - env.yaml
  - replica_count.yaml